#!/bin/bash
################################
# Author: Rum Coke
# Data  : 2015/05/15
# Ver   : 0.9.0
################################
# Send to HttpPing to URLs.
function SendHttpPing()
{
	Result=`httping -c ${TRY} ${URL} 2> /dev/null`
	echo Result | grep "${ERROR}"  && Result=''
}

# Check HttpPing Response.
function CheckHttpResponse()
{
	if [ -n "${Result}" ]
	then
		WORK=`echo ${Result} | sed -e 's/.*round-trip\ min\/avg\/max\ =\ //g' -e 's/\ ms$//g'`
		Min=`echo ${WORK} | awk -F\/ '{ print $1 }'`
		Avg=`echo ${WORK} | awk -F\/ '{ print $2 }'`
		Max=`echo ${WORK} | awk -F\/ '{ print $3 }'`
	fi	
}

################################
# Main Function
################################

# Locale Setting.
LANG=C

# Try Count.
TRY=3

# Warn and Critical.(ms)
WARN_RES='1000.0'
CRITICAL_RES='5000.0'

# Error Msg.
ERROR='No valid IPv4 or IPv6 address found for'

# URLs.
URL="http://brandear.jp/"

# Label for URLs.
URL_LABEL="Brandear"

# Exec httping.
SendHttpPing

# Response Check.
CheckHttpResponse

if [ "$1" = "autoconf" ]; then
	echo yes
       	exit 0
fi

if [ "$1" = "config" ]; then
	# Glaph Common
	echo 'graph_title Http Ping For One Site'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel response(ms)'
	echo 'graph_category network'
	echo 'graph_order response time'
	echo 'graph_scale yes'
	echo 'graph_printf %6.2lf'
	echo "graph_order ${URL_LABEL}"

	# Set Info.
	echo "${URL_LABEL}.label ${URL_LABEL}"
	echo "${URL_LABEL}.draw AREA"
	echo "${URL_LABEL}.warning ${WARN_RES}"
	echo "${URL_LABEL}.critical ${CRITICAL_RES}"
	echo "${URL_LABEL}.info Http Response."

	exit 0
fi

# Set Value.
echo "${URL_LABEL}.value ${Min}"
echo "${URL_LABEL}.value ${Avg}"
echo "${URL_LABEL}.value ${Max}"

