#!/bin/bash
i################################
# Author: Rum Coke
# Data  : 2015/05/06
# Ver   : 1.0
#################################
# for EL-USB-RT

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then

        echo 'graph_title room_temperature/himidity'
        echo 'graph_args -l 0 '
        echo 'graph_vlabel Temp/Himid'
        echo 'graph_category system'

	# temp data
        echo 'temperature.label temperature'
        echo 'temperature.draw LINE'

	#himidity data
        echo 'himidity.label himidity'
        echo 'himidity.draw LINE'

	#himidity data
        echo 'discomfort.label discomfort index'
        echo 'discomfort.draw LINE'

        print_warning temperature
        print_critical temperature
        exit 0
fi

work=`/usr/local/bin/tempsensor -s`

ROOM_TEMP=`echo ${work} | awk -F',' '{print $1}'`
ROOM_HYD=`echo ${work} | awk -F',' '{print $2}'`
ROOM_RELUX=`echo "scale=2; 0.81*$ROOM_TEMP+0.01*$ROOM_HYD*(0.99*$ROOM_TEMP-14.3)+46.3" | bc | cut -d "." -f 1`

echo "temperature.value ${ROOM_TEMP}"
echo "himidity.value ${ROOM_HYD}"
echo "discomfort.value ${ROOM_RELUX}"
